# -*- coding: utf-8 -*-
"""Milestone3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HD036MDd5gHlXMjOAeFdgDp1S3JN53tM
"""

pip install scikit-surprise

!pip install numpy==1.26.4
!pip install scikit-surprise

import pandas as pd

data = pd.read_csv("/content/cleaned_ecommerce_dataset.csv")

print(data.head())
print("Dataset shape:", data.shape)

from surprise import Dataset, Reader

# Define rating scale using purchase_count
reader = Reader(
    rating_scale=(1, int(data['purchase_count'].max()))
)

dataset = Dataset.load_from_df(
    data[['user_id', 'item_id', 'purchase_count']],
    reader
)

from surprise.model_selection import train_test_split

trainset, testset = train_test_split(
    dataset,
    test_size=0.2,
    random_state=42
)

from surprise import SVD, accuracy

svd_model = SVD(
    n_factors=50,
    n_epochs=20,
    lr_all=0.005,
    reg_all=0.02,
    random_state=42
)

svd_model.fit(trainset)

print("SVD model trained successfully")

predictions = svd_model.test(testset)

print("Baseline Model Performance:")
accuracy.rmse(predictions)
accuracy.mae(predictions)

from collections import defaultdict

def precision_recall_at_k(predictions, k=5, threshold=1):
    user_est_true = defaultdict(list)

    for uid, iid, true_r, est, _ in predictions:
        user_est_true[uid].append((est, true_r))

    precisions, recalls = {}, {}

    for uid, user_ratings in user_est_true.items():
        user_ratings.sort(key=lambda x: x[0], reverse=True)
        top_k = user_ratings[:k]

        relevant_items = sum(true_r >= threshold for _, true_r in user_ratings)
        recommended_relevant = sum(
            (est >= threshold and true_r >= threshold)
            for est, true_r in top_k
        )

        precisions[uid] = recommended_relevant / k if k else 0
        recalls[uid] = recommended_relevant / relevant_items if relevant_items else 0

    precision = sum(precisions.values()) / len(precisions)
    recall = sum(recalls.values()) / len(recalls)

    f1 = (
        2 * precision * recall / (precision + recall)
        if (precision + recall) > 0 else 0
    )

    return precision, recall, f1

p, r, f1 = precision_recall_at_k(predictions, k=5)

print(f"Precision@5: {p:.4f}")
print(f"Recall@5: {r:.4f}")
print(f"F1-Score@5: {f1:.4f}")

print("Min purchase count:", data['purchase_count'].min())
print("Max purchase count:", data['purchase_count'].max())
print("Unique purchase counts and their frequencies:\n", data['purchase_count'].value_counts().sort_index())

svd_refined = SVD(
    n_factors=100,
    n_epochs=30,
    lr_all=0.005,
    reg_all=0.01,
    random_state=42
)

svd_refined.fit(trainset)

refined_predictions = svd_refined.test(testset)

print("\nRefined Model Performance:")
accuracy.rmse(refined_predictions)
accuracy.mae(refined_predictions)

p_r, r_r, f1_r = precision_recall_at_k(refined_predictions, k=5)

print(f"Refined Precision@5: {p_r:.4f}")
print(f"Refined Recall@5: {r_r:.4f}")
print(f"Refined F1-Score@5: {f1_r:.4f}")

def recommend_products_svd(model, data, user_id, N=5):
    all_items = data['item_id'].unique()

    predictions = [
        (item, model.predict(user_id, item).est)
        for item in all_items
    ]

    predictions.sort(key=lambda x: x[1], reverse=True)
    return predictions[:N]

sample_user = data['user_id'].iloc[0]

recommendations = recommend_products_svd(
    svd_refined, data, sample_user, N=5
)

print("\nTop-5 Recommendations:")
for item, score in recommendations:
    print(item, "→", round(score, 2))

