# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQPYa7vE8vfOOEz4BVEJrYixzMzSccrm
"""

import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix

orders = pd.read_csv("/content/olist_orders_dataset.csv")
order_items = pd.read_csv("/content/olist_order_items_dataset.csv")
customers = pd.read_csv("/content/olist_customers_dataset.csv")
products = pd.read_csv("/content/olist_products_dataset.csv")

# Merge order_items with orders
data = order_items.merge(
    orders[['order_id', 'customer_id', 'order_status']],
    on='order_id',
    how='inner'
)

# Keep only delivered orders
data = data[data['order_status'] == 'delivered']

# Merge product details
data = data.merge(
    products[['product_id', 'product_category_name']],
    on='product_id',
    how='left'
)

# Merge customer details
data = data.merge(
    customers[['customer_id', 'customer_unique_id', 'customer_city', 'customer_state']],
    on='customer_id',
    how='left'
)

transactions = data[
    [
        'customer_unique_id',
        'product_id',
        'product_category_name',
        'price',
        'freight_value',
        'customer_city',
        'customer_state'
    ]
]

transactions.rename(columns={
    'customer_unique_id': 'user_id',
    'product_id': 'item_id',
    'product_category_name': 'category'
}, inplace=True)

print("\nNull values count:")
print(transactions.isnull().sum())

print("\nDuplicate rows count:")
print(transactions.duplicated().sum())

print("\nTotal rows:")
print(transactions.shape[0])

# Remove missing values
transactions.dropna(inplace=True)

# Remove duplicate rows
transactions.drop_duplicates(inplace=True)

# Reset index
transactions.reset_index(drop=True, inplace=True)

print("\nNull values count:")
print(transactions.isnull().sum())

print("\nDuplicate rows count:")
print(transactions.duplicated().sum())

print("\nTotal rows:")
print(transactions.shape[0])

# Implicit feedback
transactions['interaction'] = 1

# Purchase count per user-item
transactions['purchase_count'] = transactions.groupby(
    ['user_id', 'item_id']
)['interaction'].transform('sum')

# Keep one row per user-item
transactions.drop_duplicates(subset=['user_id', 'item_id'], inplace=True)

# Users with at least 2 interactions
valid_users = transactions['user_id'].value_counts()
transactions = transactions[
    transactions['user_id'].isin(valid_users[valid_users >= 2].index)
]

# Items with at least 2 interactions
valid_items = transactions['item_id'].value_counts()
transactions = transactions[
    transactions['item_id'].isin(valid_items[valid_items >= 2].index)
]

transactions.to_csv("cleaned_ecommerce_dataset.csv", index=False)

print("Cleaned dataset saved successfully")
print("Final dataset shape:", transactions.shape)
print(transactions.head())

# Encode users and items
user_codes = transactions['user_id'].astype('category').cat.codes
item_codes = transactions['item_id'].astype('category').cat.codes

# Create sparse matrix
user_item_sparse = csr_matrix(
    (transactions['interaction'], (user_codes, item_codes))
)

print("User–Item Matrix Shape:", user_item_sparse.shape)

